### ISSUE TITLE
Конфликт с классами Bootstrap

### ISSUE THREAD

**Issue by hatamsoyunov** [legostaev-vadim/gulp-pugbem#1]
Здравствуйте Вадим! Начал использовать ваш плагин очень крутой, удобный спасибо! Нашел небольшую проблему при использовании сторонних классов, например классы Bootsrap сетки.

![image](https://user-images.githubusercontent.com/24550178/53259033-25b90480-36df-11e9-9c8f-cde101abf41b.png)
 получаю
![image](https://user-images.githubusercontent.com/24550178/53259136-6749af80-36df-11e9-86fe-258195a03dfe.png)

да, это логично, берет класс родителя. Но есть ли какое-либо решение в таких случаях?

Спасибо

**Comment by andreypelykh** [comment]
I also faced this issue. I would suggest specifying the context of an element.
We could mark our block elements with some prefix. For example `@`. Then the code will look like this: 
```pug
.@block
  .col-lg-6
    ._element
```

And the result will be:
```html
<div class="block">
  <div class="col-lg-6">
    <div class="block__element"></div>
  </div>
</div>
```

@legostaev-vadim @hattamsoyunov Do you think it's a good idea?

**Comment by hatamsoyunov** [comment]
@andreypelykh хорошая идея, мне нравится. Надеюсь @legostaev-vadim подумает над этим )

**Comment by hatamsoyunov** [comment]
@andreypelykh а ты не придумал временное решение?

**Comment by hatamsoyunov** [comment]
Я например решил сделать так:

1. Когда обязательно нужно использовать классы bootstrap для гибкости после продакшна.
```pug
//- pug
.widget-transfer
  form._form
    ._row
      h3._subtitle Subtitle
    ._row
      ._col.col-lg-4
        // content
```
```html
<!-- html -->
<div class="widget-transfer">
  <form class="widget-transfer__form">
    <div class="widget-transfer__row">
      <h3 class="widget-transfer__subtitle">Subtitle</h3>
    </div>
    <div class="widget-transfer__row">
      <div class="widget-transfer__col col-lg-4">
        <!-- content-->
      </div>
    </div>
  </form>
</div>
```
используя миксины bootsrap задаю к __container и __row стандартные стили, дальше уже bootsrap'овские стили.
```sass
// sass
[class*="__container"]
  +make-container()
  +make-container-max-widths()

[class*="__row"]
  +make-row()

[class*="__col"]
  +make-col-ready()
```
не очень хорошая идея, но работает.

2. Когда не важно но сетка нужна, только mixin'ами для своих классов.
3. Без бутстрапа ))

**Comment by andreypelykh** [comment]
@hattamsoyunov As a workaround, I'm trying to use another package [bemto.pug](https://www.npmjs.com/package/bemto.pug). It's a set of mixins, not a plugin. But I think gulp-pugbem is better and it has cleaner syntax than using mixins. So I look forward to the block prefix feature in this plugin.

**Comment by legostaev-vadim** [comment]
Здравствуйте! Я прощу прощения, что сразу не ответил. Только сегодня увидел вашу переписку.
Я тоже столкнулся с этой проблемой, на этапе разработки плагина. К сожалению, нельзя добавить префикс к названию класса, как было предложено выше. Pug сразу выдает ошибку:

```
Class names can only contain "_", "-", a-z and 0-9, and must contain at least one of "_", or a-z
```

Чтобы в Бутстрапе всё работало нормально, нужно просто сделать бутстраповский компонент - элементом блока БЭМ. Т.е. вместо:

```pug
.block
  .col-lg-6
    ._element
```
нужно записать:

```pug
.block
  ._col.col-lg-6
    ._element
```

И в результате получим:

```html
<div class="block">
  <div class="block__col col-lg-6">
    <div class="block__element"></div>
  </div>
</div>
```

Как только мы сделали бутстраповский компонент элементом блока БЭМ, мы можем в этом компоненте указывать любое количество бутстраповских классов. Плагин устроен так, что как только он обнаруживает элемент БЭМ, все последующие классы указанные в нём, просто не учитываются при парсинге. Например:

```pug
.block
  ._col.col-lg-6.col-xl-4
    ._element
```

скомпилируется в:

```html
<div class="block">
  <div class="block__col col-lg-6 col-xl-4">
    <div class="block__element"></div>
  </div>
</div>
```

С уважением!

**Comment by hatamsoyunov** [comment]
> But I think gulp-pugbem is better and it has cleaner syntax than using mixins.

согласен, мне не понравился эти миксины, неудобно, много кода. А этот плагин спасибо @legostaev-vadim что сделал его удобным, даже с этой проблемой все равно больше плюсов чем минусы.

**Comment by hatamsoyunov** [comment]
@legostaev-vadim Спасибо что ответили! Да, я долго думал пока вы не отвечали и получается как раз нашел правильное решение )) Жаль конечно что нет других вариантов, но все равно самый удобный для pug+bem, так что буду просто делать как делал.

Спасибо!

**Comment by legostaev-vadim** [comment]
Поскольку плагином продолжает пользоваться какое-то количество людей, было бы не совсем правильно, оставить эту проблему без решения.

Начиная с версии **2.2.0**, теперь вы можете указывать свои префиксы для блоков в свойстве **b**:

```js
var pugbem = require('gulp-pugbem');

// block prefix
pugbem.b = 'my-';
```

или

```js
// default 'b-'
pugbem.b = true;
```

Имя префикса может состоять из букв, цифр, нижнего подчеркивания и дефиса. После этого, только классы начинающиеся с вашего префикса, будут учитываться при парсинге блоков **BEM**. Классы блоков без префикса будут пропускаться, при любой глубине вложенности элементов. Это позволит решить проблему связанную с использованием внешних css-библиотек, типа Bootstrap, с большой глубиной вложенности элементов. Например:

**без префикса:**

*test.pug*

```pug
.block
  .row
    .col-lg-8.col-xl-4
      .row
        .col-lg-8.col-xl-3
          ._elem1
    .col-lg-4.col-xl-8
      ._elem2
```

*скомпилируется в:*

```html
<div class="block">
  <div class="row">
    <div class="col-lg-8 col-xl-4">
      <div class="row">
        <div class="col-lg-8 col-xl-3">
          <!-- блоком является ближайший родительский элемент с классом 'col-lg-8' в файле 'test.pug' -->
          <div class="col-lg-8__elem1"></div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-xl-8">
      <!-- блоком является ближайший родительский элемент с классом 'col-lg-4' в файле 'test.pug' -->
      <div class="col-lg-4__elem2"></div>
    </div>
  </div>
</div>
```

**с пользовательским префиксом:**

*gulpfile.js*

```js
var pugbem = require('gulp-pugbem');
pugbem.b = true; // default 'b-'
```

*test.pug*

```pug
//- добавляем префикс к названию блока
.b-block
  .row
    .col-lg-8.col-xl-4
      .row
        .col-lg-8.col-xl-3
          ._elem1
    .col-lg-4.col-xl-8
      ._elem2
```

*скомпилируется в:*

```html
<!-- пользовательский префикс не попадает в итоговый html -->
<div class="block">
  <div class="row">
    <div class="col-lg-8 col-xl-4">
      <div class="row">
        <div class="col-lg-8 col-xl-3">
         <!-- блоком является элемент с префиксом 'b-' в файле 'test.pug' -->
          <div class="block__elem1"></div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-xl-8">
      <!-- блоком является элемент с префиксом 'b-' в файле 'test.pug' -->
      <div class="block__elem2"></div>
    </div>
  </div>
</div>
```

**ещё пример:**

```pug
//- при использовании пользовательских префиксов, они должны быть добавлены к имени каждого блока BEM.
//- классы блоков без префикса, не учитываются в пространстве имён BEM при компиляции!
.b-block1
  .class1.class2
    .class3
      ._elem1
    .b-block2
      ._elem2
```

*скомпилируется в:*

```html
<div class="block1">
  <div class="class1 class2">
    <div class="class3">
      <div class="block1__elem1"></div>
    </div>
    <div class="block2">
      <div class="block2__elem2"></div>
    </div>
  </div>
</div>
```

**Comment by hatamsoyunov** [comment]
Воуу, круто )) спасибо!
